"""initial_schema

Revision ID: 4fc324c18025
Revises: 
Create Date: 2026-08-06 02:43:45.872713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4fc324c18025'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_generations', 'prompt',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('ai_generations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_ai_generations_instructor_id'), 'ai_generations', ['instructor_id'], unique=False)
    op.drop_constraint(op.f('ai_generations_instructor_id_fkey'), 'ai_generations', type_='foreignkey')
    op.create_foreign_key(None, 'ai_generations', 'users', ['instructor_id'], ['id'])
    op.alter_column('session_registrations', 'attended',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('sessions', 'reminder_sent',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'reminder_sent',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('session_registrations', 'attended',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'ai_generations', type_='foreignkey')
    op.create_foreign_key(op.f('ai_generations_instructor_id_fkey'), 'ai_generations', 'users', ['instructor_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_ai_generations_instructor_id'), table_name='ai_generations')
    op.alter_column('ai_generations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ai_generations', 'prompt',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    # ### end Alembic commands ###
